### ISSUE TITLE
Improve semantic release github action workflow

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/cookiecutter-python#42]
in the semantic release github action workflow, allow it for push and for pull_request, exemplo:

```
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```

The current step for semantic release command should be executed just for workflow dispatch:

`if: ${{ github.event_name == 'workflow_dispatch' }}`

Additionally, before this step, we should add a copy of the semantic release step, but just for non workflow dispatch event:

`if: ${{ github.event_name != 'workflow_dispatch' }}`

this step should run for `--dry` instead of `--ci`
